#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# Immuvi /classify-inspiration skill — one-line installer
#
#   curl -fsSL https://immuvi-command-center.vercel.app/install-skill.sh | bash
#
# Installs everything a teammate needs to run the /classify-inspiration
# skill in their own Claude Code:
#   • ffmpeg + yt-dlp (Homebrew)
#   • psycopg2-binary + requests + playwright (pip, --user)
#   • Playwright Chromium
#   • SKILL.md + fb_ad_classifier.py under ~/.claude/skills/
#   • Env file at ~/.classify-inspiration.env (chmod 600)
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

INSTALLER_VERSION="1.0.0"
ASSET_BASE="https://immuvi-command-center.vercel.app/team-skill"
SKILL_DIR="$HOME/.claude/skills/classify-inspiration"
ENV_FILE="$HOME/.classify-inspiration.env"

# Colors
BOLD=$'\e[1m'; RED=$'\e[31m'; GRN=$'\e[32m'; YLW=$'\e[33m'; BLU=$'\e[36m'; OFF=$'\e[0m'

say()   { echo "${BLU}▸${OFF} $*"; }
ok()    { echo "${GRN}✓${OFF} $*"; }
warn()  { echo "${YLW}⚠${OFF} $*"; }
fail()  { echo "${RED}✗${OFF} $*"; exit 1; }

echo ""
echo "${BOLD}Immuvi /classify-inspiration — installer v${INSTALLER_VERSION}${OFF}"
echo ""
echo "This will install about 200 MB of dependencies (ffmpeg, Playwright Chromium, etc.)"
echo "and set up your Supabase credentials. Takes ~3 minutes on a fast connection."
echo ""

# ── 0. Sanity checks ───────────────────────────────────────────────────────
if [[ "$(uname -s)" != "Darwin" ]]; then
  fail "This installer is macOS-only. You're on $(uname -s)."
fi
if ! command -v brew >/dev/null 2>&1; then
  fail "Homebrew not installed. Install it from https://brew.sh and re-run."
fi
if ! command -v python3 >/dev/null 2>&1; then
  fail "python3 not on PATH. Install via: brew install python@3.12"
fi
if ! command -v claude >/dev/null 2>&1; then
  warn "Claude Code CLI not detected. Install it before the skill can be used."
fi

# ── 1. Prompt for Supabase creds ───────────────────────────────────────────
echo "${BOLD}Step 1 — Supabase credentials${OFF}"
echo "Gaurav will send you two values over Slack/DM. Paste them below."
echo "(Input is hidden — that's normal.)"
echo ""

read -rsp "  SUPABASE_SERVICE_ROLE_KEY: " SUPABASE_SERVICE_ROLE_KEY
echo ""
read -rsp "  SUPABASE_DB_PASSWORD:      " SUPABASE_DB_PASSWORD
echo ""
echo ""

if [[ -z "${SUPABASE_SERVICE_ROLE_KEY}" || -z "${SUPABASE_DB_PASSWORD}" ]]; then
  fail "Both values are required. Re-run and paste them when prompted."
fi

# Basic shape check — service role keys are JWTs (long, 3 dot-separated parts)
if [[ ! "$SUPABASE_SERVICE_ROLE_KEY" =~ ^eyJ.+\..+\..+$ ]]; then
  warn "SUPABASE_SERVICE_ROLE_KEY doesn't look like a JWT (should start with 'eyJ'). Continuing anyway."
fi

# ── 2. Write env file (chmod 600) ──────────────────────────────────────────
say "Writing env file to $ENV_FILE"
cat > "$ENV_FILE" <<ENVEOF
# Immuvi /classify-inspiration skill — DO NOT COMMIT or share
# Generated by install-skill.sh v${INSTALLER_VERSION} at $(date -u +%Y-%m-%dT%H:%M:%SZ)
SUPABASE_URL=https://bfsvczgnnjwqzvrluqhw.supabase.co
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
SUPABASE_DB_URL=postgresql://postgres:${SUPABASE_DB_PASSWORD}@db.bfsvczgnnjwqzvrluqhw.supabase.co:5432/postgres
ENVEOF
chmod 600 "$ENV_FILE"
ok "Env written (permissions: 600, readable only by you)"

# ── 3. System binaries ─────────────────────────────────────────────────────
say "Installing ffmpeg + yt-dlp via Homebrew"
brew list ffmpeg >/dev/null 2>&1 || brew install ffmpeg >/dev/null
brew list yt-dlp >/dev/null 2>&1 || brew install yt-dlp >/dev/null
ok "ffmpeg $(ffmpeg -version | head -1 | awk '{print $3}'), yt-dlp $(yt-dlp --version)"

# ── 4. Python packages ─────────────────────────────────────────────────────
say "Installing Python packages (psycopg2-binary, requests, playwright)"
# Use --user to avoid needing sudo; --break-system-packages for macOS PEP 668 systems
pip3 install -q --user --break-system-packages psycopg2-binary requests playwright 2>/dev/null \
  || pip3 install -q --user psycopg2-binary requests playwright
ok "Python packages installed"

# ── 5. Playwright Chromium (only if not already present) ───────────────────
say "Installing Playwright Chromium (skipped if already present)"
python3 -m playwright install chromium >/dev/null 2>&1 || {
  warn "Playwright chromium install returned non-zero. Trying again with visible output…"
  python3 -m playwright install chromium
}
ok "Playwright Chromium ready"

# ── 6. Download skill files ────────────────────────────────────────────────
say "Downloading skill files to $SKILL_DIR"
mkdir -p "$SKILL_DIR"
curl -fsSL "${ASSET_BASE}/SKILL.md"            -o "$SKILL_DIR/SKILL.md"
curl -fsSL "${ASSET_BASE}/fb_ad_classifier.py" -o "$SKILL_DIR/fb_ad_classifier.py"
ok "SKILL.md + fb_ad_classifier.py installed"

# ── 7. Smoke test — can we reach Supabase? ─────────────────────────────────
say "Running a quick smoke test against Supabase"
SMOKE_OUT=$(python3 - <<PYEOF 2>&1
import os, sys
os.environ.update(dict(line.strip().split("=", 1) for line in open("${ENV_FILE}") if line.strip() and not line.startswith("#")))
try:
    import psycopg2
    conn = psycopg2.connect(os.environ["SUPABASE_DB_URL"], connect_timeout=10)
    cur = conn.cursor(); cur.execute("select count(*) from public.products")
    count = cur.fetchone()[0]
    cur.close(); conn.close()
    print(f"OK {count}")
except Exception as e:
    print(f"FAIL {e}")
    sys.exit(1)
PYEOF
) || true

if [[ "$SMOKE_OUT" == OK* ]]; then
  PRODUCTS_COUNT="${SMOKE_OUT#OK }"
  ok "Connected to Supabase — can see $PRODUCTS_COUNT product(s)"
else
  warn "Supabase smoke test did not pass: $SMOKE_OUT"
  warn "Credentials might be wrong. Edit $ENV_FILE and try \`/classify-inspiration\` anyway."
fi

# ── Done ───────────────────────────────────────────────────────────────────
echo ""
echo "${BOLD}${GRN}🎉 Installation complete${OFF}"
echo ""
echo "Next steps:"
echo "  1. Open Claude Code in any terminal"
echo "  2. Type ${BOLD}/classify-inspiration${OFF}"
echo "  3. It will pick up pending URLs queued from the Immuvi dashboard"
echo "     (https://immuvi-command-center.vercel.app)"
echo ""
echo "To update later:"
echo "  curl -fsSL https://immuvi-command-center.vercel.app/install-skill.sh | bash"
echo ""
echo "To uninstall:"
echo "  rm -rf ${SKILL_DIR} ${ENV_FILE}"
echo ""
