// Vercel Serverless Function — generates a pre-filled installer for the
// /classify-inspiration skill on demand, reading secrets from Vercel env vars
// so nothing sensitive ever lives in git.
//
// Usage (what teammates paste in their Terminal):
//   Mac:     curl -fsSL 'https://immuvi-command-center.vercel.app/api/install-skill?t=<secret>' | bash
//   Win+WSL: curl -fsSL 'https://immuvi-command-center.vercel.app/api/install-skill?t=<secret>&os=wsl' | bash
//
// The `t` query param must match INSTALL_SKILL_SECRET (rotatable env var).
// If it doesn't, we return 401 and DO NOT include any credentials in the
// response body. Even the error message is safe to paste publicly.
//
// Env vars this function reads (set via `vercel env add`):
//   - INSTALL_SKILL_SECRET       : the shared "team secret"; rotate if leaked
//   - SUPABASE_SERVICE_ROLE_KEY  : piped into the teammate's ~/.classify-inspiration.env
//   - SUPABASE_DB_PASSWORD       : same
//
// OS branching:
//   - mac  (default): uses Homebrew for ffmpeg/yt-dlp, expects macOS/Darwin.
//   - wsl           : uses apt-get (sudo prompt), expects Linux/WSL. This is
//                     the supported path for Windows teammates because the
//                     skill itself is bash-only (psql, heredocs, $HOME, …)
//                     and would require a full PowerShell rewrite to run
//                     natively on Windows — not worth it for ~5min of WSL.

export default async function handler(req, res) {
  // No caching — if creds rotate, the next curl must see fresh values.
  res.setHeader('Cache-Control', 'no-store, max-age=0');

  const provided = (req.query && req.query.t) || '';
  const expected = process.env.INSTALL_SKILL_SECRET || '';
  if (!expected) {
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.status(500).send('Installer disabled: INSTALL_SKILL_SECRET not configured.\n');
    return;
  }
  if (provided.length !== expected.length || !timingSafeEqual(provided, expected)) {
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.status(401).send('Unauthorized. Contact Gaurav for the correct install link.\n');
    return;
  }

  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const dbPassword = process.env.SUPABASE_DB_PASSWORD;
  if (!serviceKey || !dbPassword) {
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.status(500).send('Installer misconfigured: SUPABASE_* env vars missing on the server.\n');
    return;
  }

  // Normalize os param.
  // Accept mac/macos/darwin, wsl/linux/ubuntu/debian, or win/windows/ps/powershell.
  // Default: mac.
  const osRaw = String((req.query && req.query.os) || 'mac').toLowerCase();
  let os = 'mac';
  if (/^(wsl|linux|ubuntu|debian)/.test(osRaw))        os = 'wsl';
  else if (/^(win|windows|ps|powershell)/.test(osRaw)) os = 'win';

  const version = `1.3.0-prefilled-${os}`;
  const assetBase = `https://immuvi-command-center.vercel.app/team-skill`;
  const generatedAt = new Date().toISOString();

  let script, contentType;
  if (os === 'win') {
    // PowerShell path: single-quote escape doubles the quote.
    const SRK_PS = psq(serviceKey);
    const DBP_PS = psq(dbPassword);
    script = buildWindowsInstaller({ SRK: SRK_PS, DBP: DBP_PS, version, assetBase, generatedAt });
    contentType = 'text/plain; charset=utf-8';  // `irm | iex` reads it as a string
  } else {
    // bash path: use the bash single-quote escape helper.
    const SRK = sq(serviceKey);
    const DBP = sq(dbPassword);
    script = os === 'wsl'
      ? buildWslInstaller({ SRK, DBP, version, assetBase, generatedAt })
      : buildMacInstaller({ SRK, DBP, version, assetBase, generatedAt });
    contentType = 'text/x-shellscript; charset=utf-8';
  }

  res.setHeader('Content-Type', contentType);
  res.status(200).send(script);
}

// ────────────────────────────────────────────────────────────────────────────
// Windows installer (native Windows + Claude Desktop)
//
// Targets Claude Desktop on Windows, which reads skills from
// C:\Users\<name>\.claude\skills\<skill>\SKILL.md. Uses winget for system
// packages. Ensures Git Bash is available so the skill's bash commands
// (psql, source, heredocs, etc.) can execute on Windows without WSL.
//
// Teammate runs one line in PowerShell:
//   irm 'https://.../api/install-skill?t=<secret>&os=win' | iex
// ────────────────────────────────────────────────────────────────────────────
function buildWindowsInstaller({ SRK, DBP, version, assetBase, generatedAt }) {
  return `# ─────────────────────────────────────────────────────────────────────
# Immuvi /classify-inspiration skill — PRE-FILLED installer (Windows)
# Generated by api/install-skill.js at ${generatedAt}
# Installer version: ${version}
#
# Installs the skill where Claude Desktop on Windows reads it:
#   %USERPROFILE%\\.claude\\skills\\classify-inspiration\\SKILL.md
# Dependencies via winget. The skill uses bash internally; Git Bash
# (shipped with Git for Windows) is installed if missing so Claude
# can run the skill's bash commands natively.
# ─────────────────────────────────────────────────────────────────────

$ErrorActionPreference = 'Stop'
$ProgressPreference    = 'SilentlyContinue'   # speeds up Invoke-WebRequest

$INSTALLER_VERSION = '${version}'
$ASSET_BASE        = '${assetBase}'
$ENV_FILE          = Join-Path $env:USERPROFILE '.classify-inspiration.env'

# Embedded credentials — only this teammate's machine sees them.
$SUPABASE_SERVICE_ROLE_KEY = ${SRK}
$SUPABASE_DB_PASSWORD      = ${DBP}

function Say   { param($m) Write-Host ("  > $m") -ForegroundColor Cyan }
function OK    { param($m) Write-Host ("  OK $m") -ForegroundColor Green }
function Warn  { param($m) Write-Host ("  ! $m") -ForegroundColor Yellow }
function Fail  { param($m) Write-Host ("  X $m") -ForegroundColor Red; exit 1 }

Write-Host ""
Write-Host "Immuvi /classify-inspiration - Windows installer v$INSTALLER_VERSION" -ForegroundColor White
Write-Host ""
Write-Host "Installing dependencies (Python, ffmpeg, yt-dlp, Git Bash, Playwright) and"
Write-Host "setting up your Supabase credentials. ~5 minutes on first run."
Write-Host ""

# ── 0. Sanity ──────────────────────────────────────────────────────────────
if ($PSVersionTable.PSVersion.Major -lt 5) {
  Fail "PowerShell 5.1+ required. You are on $($PSVersionTable.PSVersion)."
}
if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
  Fail "winget not found. Install 'App Installer' from the Microsoft Store first, then re-run."
}

# Helper: install a winget package if its command isn't already on PATH.
function Ensure-Winget {
  param([string]$Id, [string]$ProbeCmd, [string]$DisplayName)
  if (Get-Command $ProbeCmd -ErrorAction SilentlyContinue) {
    OK "$DisplayName already installed"
    return
  }
  Say "Installing $DisplayName via winget..."
  try {
    winget install --id $Id --silent --accept-package-agreements --accept-source-agreements --source winget | Out-Null
    OK "$DisplayName installed"
  } catch {
    Warn "$DisplayName install returned non-zero. Continuing — you may need to install manually."
  }
}

# ── 1. Write env file (locked-down ACL, equivalent of chmod 600) ──────────
Say "Writing env file to $ENV_FILE"
$env_content = @"
# Immuvi /classify-inspiration skill - DO NOT COMMIT, DO NOT share
SUPABASE_URL=https://bfsvczgnnjwqzvrluqhw.supabase.co
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
SUPABASE_DB_PASSWORD=$SUPABASE_DB_PASSWORD
SUPABASE_DB_URL=postgresql://postgres:$SUPABASE_DB_PASSWORD@db.bfsvczgnnjwqzvrluqhw.supabase.co:5432/postgres
"@
Set-Content -Path $ENV_FILE -Value $env_content -Encoding UTF8
# Break inheritance and grant only the current user read/write (Windows equiv of chmod 600)
try {
  icacls $ENV_FILE /inheritance:r /grant:r "$($env:USERNAME):F" | Out-Null
} catch {
  Warn "Could not restrict ACL on $ENV_FILE. File is written but other users on this PC could read it."
}
OK "Env file written"

# ── 2. System deps via winget ──────────────────────────────────────────────
Ensure-Winget -Id 'Python.Python.3.12'      -ProbeCmd 'python'  -DisplayName 'Python 3.12'
Ensure-Winget -Id 'Gyan.FFmpeg'              -ProbeCmd 'ffmpeg'  -DisplayName 'ffmpeg'
Ensure-Winget -Id 'yt-dlp.yt-dlp'            -ProbeCmd 'yt-dlp'  -DisplayName 'yt-dlp'
# Git for Windows includes Git Bash, which the skill's bash commands need to run.
Ensure-Winget -Id 'Git.Git'                  -ProbeCmd 'bash'    -DisplayName 'Git for Windows (includes Git Bash)'

# Refresh PATH so the just-installed binaries are callable in this session
$env:Path = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ';' +
            [System.Environment]::GetEnvironmentVariable('Path','User')

# ── 3. Python packages ─────────────────────────────────────────────────────
Say "Installing Python packages (psycopg2-binary, requests, playwright)"
try {
  & python -m pip install --user --quiet psycopg2-binary requests playwright
  OK "Python packages installed"
} catch {
  Warn "pip install returned non-zero. The smoke test below will reveal if it actually worked."
}

# ── 4. Playwright Chromium ─────────────────────────────────────────────────
Say "Installing Playwright Chromium (skipped if already present)"
try {
  & python -m playwright install chromium | Out-Null
  OK "Playwright Chromium ready"
} catch {
  Warn "Playwright chromium install had issues. Try manually: python -m playwright install chromium"
}

# ── 5. Download skill files ────────────────────────────────────────────────
Say "Downloading skill files"
$SkillsRoot = Join-Path $env:USERPROFILE '.claude\\skills'
# /classify-inspiration
$CI_Dir = Join-Path $SkillsRoot 'classify-inspiration'
New-Item -ItemType Directory -Force -Path $CI_Dir | Out-Null
Invoke-WebRequest -UseBasicParsing "$ASSET_BASE/SKILL.md"            -OutFile (Join-Path $CI_Dir 'SKILL.md')
Invoke-WebRequest -UseBasicParsing "$ASSET_BASE/fb_ad_classifier.py" -OutFile (Join-Path $CI_Dir 'fb_ad_classifier.py')
OK "/classify-inspiration installed"
# /clickup-creative-pipeline
$CP_Dir = Join-Path $SkillsRoot 'clickup-creative-pipeline'
New-Item -ItemType Directory -Force -Path $CP_Dir | Out-Null
Invoke-WebRequest -UseBasicParsing "$ASSET_BASE/clickup-creative-pipeline/SKILL.md" -OutFile (Join-Path $CP_Dir 'SKILL.md')
OK "/clickup-creative-pipeline installed"

# ── 6. Supabase smoke test ─────────────────────────────────────────────────
Say "Running a quick smoke test against Supabase"
$smoke = & python -c "
import os
for line in open(r'$ENV_FILE'):
    line = line.strip()
    if not line or line.startswith('#') or '=' not in line: continue
    k, v = line.split('=', 1); os.environ[k] = v
try:
    import psycopg2
    conn = psycopg2.connect(os.environ['SUPABASE_DB_URL'], connect_timeout=10)
    cur = conn.cursor(); cur.execute('select count(*) from public.products')
    print('OK', cur.fetchone()[0])
    cur.close(); conn.close()
except Exception as e:
    print('FAIL', e)
" 2>&1

if ($smoke -match '^OK') {
  OK "Connected to Supabase - $($smoke -replace '^OK ','') product(s) visible"
} else {
  Warn "Supabase smoke test did not pass: $smoke"
  Warn "The skill is installed; credentials may need to be re-checked."
}

# ── Done ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "IMPORTANT:" -ForegroundColor Yellow
Write-Host "  1. Fully quit Claude Desktop (right-click tray icon -> Quit, not just close window)"
Write-Host "  2. Reopen Claude Desktop"
Write-Host "  3. In a new chat, type '/' and try:"
Write-Host "       /classify-inspiration       (classify a URL queued from Immuvi dashboard)"
Write-Host "       /clickup-creative-pipeline  (bulk-classify a ClickUp list with Drive-Linked tasks)"
Write-Host ""
Write-Host "To update later: re-run this same command."
Write-Host "To uninstall:   Remove-Item -Recurse '$CI_Dir','$CP_Dir'; Remove-Item '$ENV_FILE'"
Write-Host ""
`;
}

// ────────────────────────────────────────────────────────────────────────────
// Mac installer (macOS / Darwin, Homebrew for system deps)
// ────────────────────────────────────────────────────────────────────────────
function buildMacInstaller({ SRK, DBP, version, assetBase, generatedAt }) {
  return `#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# Immuvi /classify-inspiration skill — PRE-FILLED installer (macOS)
# Generated by api/install-skill.js at ${generatedAt}
# Installer version: ${version}
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

INSTALLER_VERSION=${sq(version)}
ASSET_BASE=${sq(assetBase)}
ENV_FILE="$HOME/.classify-inspiration.env"

SUPABASE_SERVICE_ROLE_KEY=${SRK}
SUPABASE_DB_PASSWORD=${DBP}

BOLD=$'\\e[1m'; RED=$'\\e[31m'; GRN=$'\\e[32m'; YLW=$'\\e[33m'; BLU=$'\\e[36m'; OFF=$'\\e[0m'
say()  { echo "\${BLU}▸\${OFF} $*"; }
ok()   { echo "\${GRN}✓\${OFF} $*"; }
warn() { echo "\${YLW}⚠\${OFF} $*"; }
fail() { echo "\${RED}✗\${OFF} $*"; exit 1; }

echo ""
echo "\${BOLD}Immuvi /classify-inspiration — macOS installer v\${INSTALLER_VERSION}\${OFF}"
echo ""
echo "Installing ~200 MB of dependencies (ffmpeg, Playwright Chromium, etc.)"
echo "and setting up your Supabase credentials. ~3 minutes."
echo ""

if [[ "$(uname -s)" != "Darwin" ]]; then
  fail "This is the macOS installer but you're on $(uname -s). If you're on Windows, ask Gaurav for the WSL link instead."
fi
if ! command -v brew >/dev/null 2>&1; then
  fail "Homebrew not installed. Install it from https://brew.sh and re-run."
fi
if ! command -v python3 >/dev/null 2>&1; then
  fail "python3 not on PATH. Install via: brew install python@3.12"
fi
if ! command -v claude >/dev/null 2>&1; then
  warn "Claude Code CLI not detected. Install it before the skill can be used."
fi

say "Writing env file to $ENV_FILE"
umask 077
cat > "$ENV_FILE" <<ENVEOF
SUPABASE_URL=https://bfsvczgnnjwqzvrluqhw.supabase.co
SUPABASE_SERVICE_ROLE_KEY=\${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_DB_PASSWORD=\${SUPABASE_DB_PASSWORD}
SUPABASE_DB_URL=postgresql://postgres:\${SUPABASE_DB_PASSWORD}@db.bfsvczgnnjwqzvrluqhw.supabase.co:5432/postgres
ENVEOF
chmod 600 "$ENV_FILE"
umask 022
ok "Env written (permissions: 600)"

say "Installing ffmpeg + yt-dlp via Homebrew"
brew list ffmpeg >/dev/null 2>&1 || brew install ffmpeg >/dev/null
brew list yt-dlp >/dev/null 2>&1 || brew install yt-dlp >/dev/null
ok "ffmpeg $(ffmpeg -version | head -1 | awk '{print $3}'), yt-dlp $(yt-dlp --version)"

say "Installing Python packages (psycopg2-binary, requests, playwright)"
pip3 install -q --user --break-system-packages psycopg2-binary requests playwright 2>/dev/null \\
  || pip3 install -q --user psycopg2-binary requests playwright
ok "Python packages installed"

say "Installing Playwright Chromium (skipped if already present)"
python3 -m playwright install chromium >/dev/null 2>&1 || {
  warn "Playwright chromium install returned non-zero. Retrying with output…"
  python3 -m playwright install chromium
}
ok "Playwright Chromium ready"

say "Downloading skill files to \${HOME}/.claude/skills/"
SKILLS_ROOT="\${HOME}/.claude/skills"
# /classify-inspiration (Supabase-queued competitor URL classifier)
mkdir -p "\${SKILLS_ROOT}/classify-inspiration"
curl -fsSL "\${ASSET_BASE}/SKILL.md"            -o "\${SKILLS_ROOT}/classify-inspiration/SKILL.md"
curl -fsSL "\${ASSET_BASE}/fb_ad_classifier.py" -o "\${SKILLS_ROOT}/classify-inspiration/fb_ad_classifier.py"
ok "/classify-inspiration installed"
# /clickup-creative-pipeline (bulk-classify any ClickUp list with Drive-Linked tasks)
mkdir -p "\${SKILLS_ROOT}/clickup-creative-pipeline"
curl -fsSL "\${ASSET_BASE}/clickup-creative-pipeline/SKILL.md" -o "\${SKILLS_ROOT}/clickup-creative-pipeline/SKILL.md"
ok "/clickup-creative-pipeline installed"

say "Running a quick smoke test against Supabase"
SMOKE_OUT=$(python3 - <<PYEOF 2>&1
import os, sys
os.environ.update(dict(line.strip().split("=", 1) for line in open("\${ENV_FILE}") if line.strip() and not line.startswith("#")))
try:
    import psycopg2
    conn = psycopg2.connect(os.environ["SUPABASE_DB_URL"], connect_timeout=10)
    cur = conn.cursor(); cur.execute("select count(*) from public.products")
    count = cur.fetchone()[0]
    cur.close(); conn.close()
    print(f"OK {count}")
except Exception as e:
    print(f"FAIL {e}")
    sys.exit(1)
PYEOF
) || true

if [[ "$SMOKE_OUT" == OK* ]]; then
  ok "Connected to Supabase — can see \${SMOKE_OUT#OK } product(s)"
else
  warn "Supabase smoke test did not pass: $SMOKE_OUT"
fi

echo ""
echo "\${BOLD}\${GRN}🎉 Installation complete — 2 skills installed\${OFF}"
echo ""
echo "Open Claude Code (or Claude Desktop) and try:"
echo "  \${BOLD}/classify-inspiration\${OFF}       — classify a URL queued from the Immuvi dashboard"
echo "  \${BOLD}/clickup-creative-pipeline\${OFF}  — bulk-classify any ClickUp list with Drive-Linked tasks"
echo ""
`;
}

// ────────────────────────────────────────────────────────────────────────────
// WSL installer (Linux/Ubuntu on Windows, apt-get for system deps)
// ────────────────────────────────────────────────────────────────────────────
function buildWslInstaller({ SRK, DBP, version, assetBase, generatedAt }) {
  return `#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# Immuvi /classify-inspiration skill — PRE-FILLED installer (WSL / Linux)
# Generated by api/install-skill.js at ${generatedAt}
# Installer version: ${version}
#
# Intended audience: Windows users running WSL (Ubuntu/Debian) or native
# Linux. Uses apt-get for system packages. The sudo prompts during the
# apt-get steps are the ONLY times this installer will pause — your
# Supabase credentials are already baked into this script URL.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

INSTALLER_VERSION=${sq(version)}
ASSET_BASE=${sq(assetBase)}
ENV_FILE="$HOME/.classify-inspiration.env"

SUPABASE_SERVICE_ROLE_KEY=${SRK}
SUPABASE_DB_PASSWORD=${DBP}

BOLD=$'\\e[1m'; RED=$'\\e[31m'; GRN=$'\\e[32m'; YLW=$'\\e[33m'; BLU=$'\\e[36m'; OFF=$'\\e[0m'
say()  { echo "\${BLU}▸\${OFF} $*"; }
ok()   { echo "\${GRN}✓\${OFF} $*"; }
warn() { echo "\${YLW}⚠\${OFF} $*"; }
fail() { echo "\${RED}✗\${OFF} $*"; exit 1; }

echo ""
echo "\${BOLD}Immuvi /classify-inspiration — WSL / Linux installer v\${INSTALLER_VERSION}\${OFF}"
echo ""
echo "Installing ~250 MB of dependencies via apt-get + pip + Playwright."
echo "You'll be prompted for your sudo password once (for apt-get)."
echo "~4 minutes on a first run."
echo ""

# ── Detect environment ────────────────────────────────────────────────────
KERNEL=$(uname -s)
if [[ "$KERNEL" != "Linux" ]]; then
  fail "This is the WSL/Linux installer but you're on $KERNEL. On macOS, use the Mac link instead."
fi
if grep -qi "microsoft\\|wsl" /proc/version 2>/dev/null; then
  ok "Running inside WSL — good"
else
  warn "This looks like native Linux (not WSL). Installer will still work."
fi
if ! command -v apt-get >/dev/null 2>&1; then
  fail "apt-get not found. This installer supports Debian/Ubuntu-based distros. Ask Gaurav for help if you're on something else."
fi
if ! command -v python3 >/dev/null 2>&1; then
  say "Installing python3 first (required)"
  sudo apt-get update -qq && sudo apt-get install -y python3 python3-pip
fi
if ! command -v claude >/dev/null 2>&1; then
  warn "Claude Code CLI not detected. Install it before the skill can be used."
fi

# ── 1. Env file (chmod 600) ───────────────────────────────────────────────
say "Writing env file to $ENV_FILE"
umask 077
cat > "$ENV_FILE" <<ENVEOF
SUPABASE_URL=https://bfsvczgnnjwqzvrluqhw.supabase.co
SUPABASE_SERVICE_ROLE_KEY=\${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_DB_PASSWORD=\${SUPABASE_DB_PASSWORD}
SUPABASE_DB_URL=postgresql://postgres:\${SUPABASE_DB_PASSWORD}@db.bfsvczgnnjwqzvrluqhw.supabase.co:5432/postgres
ENVEOF
chmod 600 "$ENV_FILE"
umask 022
ok "Env written (permissions: 600)"

# ── 2. System packages via apt-get ────────────────────────────────────────
say "Installing system packages: ffmpeg, postgresql-client, python3-pip, curl"
# apt-get is idempotent — already-installed packages are no-ops.
sudo apt-get update -qq
sudo apt-get install -y -qq ffmpeg postgresql-client python3-pip curl >/dev/null
ok "apt packages installed"

# yt-dlp isn't reliably packaged on all Ubuntu releases — install via pip for a consistent version.
say "Installing yt-dlp via pip (more up-to-date than apt)"
pip3 install -q --user --break-system-packages yt-dlp 2>/dev/null \\
  || pip3 install -q --user yt-dlp
# Ensure ~/.local/bin is on PATH for this session so yt-dlp is callable.
export PATH="$HOME/.local/bin:$PATH"
ok "yt-dlp $(yt-dlp --version 2>/dev/null || echo '(installed; add ~/.local/bin to PATH)')"

# ── 3. Python packages (Playwright deps come next) ───────────────────────
say "Installing Python packages (psycopg2-binary, requests, playwright)"
pip3 install -q --user --break-system-packages psycopg2-binary requests playwright 2>/dev/null \\
  || pip3 install -q --user psycopg2-binary requests playwright
ok "Python packages installed"

# ── 4. Playwright Chromium + system deps ─────────────────────────────────
say "Installing Playwright Chromium + its system libraries (will prompt for sudo)"
# --with-deps handles the long list of shared libs Chromium needs on Linux.
python3 -m playwright install --with-deps chromium 2>/dev/null || {
  warn "--with-deps failed (maybe no sudo). Trying without system deps…"
  python3 -m playwright install chromium
}
ok "Playwright Chromium ready"

# ── 5. Download skill files ───────────────────────────────────────────────
say "Downloading skill files to \${HOME}/.claude/skills/"
SKILLS_ROOT="\${HOME}/.claude/skills"
mkdir -p "\${SKILLS_ROOT}/classify-inspiration"
curl -fsSL "\${ASSET_BASE}/SKILL.md"            -o "\${SKILLS_ROOT}/classify-inspiration/SKILL.md"
curl -fsSL "\${ASSET_BASE}/fb_ad_classifier.py" -o "\${SKILLS_ROOT}/classify-inspiration/fb_ad_classifier.py"
ok "/classify-inspiration installed"
mkdir -p "\${SKILLS_ROOT}/clickup-creative-pipeline"
curl -fsSL "\${ASSET_BASE}/clickup-creative-pipeline/SKILL.md" -o "\${SKILLS_ROOT}/clickup-creative-pipeline/SKILL.md"
ok "/clickup-creative-pipeline installed"

# ── 6. Supabase smoke test ────────────────────────────────────────────────
say "Running a quick smoke test against Supabase"
SMOKE_OUT=$(python3 - <<PYEOF 2>&1
import os, sys
os.environ.update(dict(line.strip().split("=", 1) for line in open("\${ENV_FILE}") if line.strip() and not line.startswith("#")))
try:
    import psycopg2
    conn = psycopg2.connect(os.environ["SUPABASE_DB_URL"], connect_timeout=10)
    cur = conn.cursor(); cur.execute("select count(*) from public.products")
    count = cur.fetchone()[0]
    cur.close(); conn.close()
    print(f"OK {count}")
except Exception as e:
    print(f"FAIL {e}")
    sys.exit(1)
PYEOF
) || true

if [[ "$SMOKE_OUT" == OK* ]]; then
  ok "Connected to Supabase — can see \${SMOKE_OUT#OK } product(s)"
else
  warn "Supabase smoke test did not pass: $SMOKE_OUT"
  warn "Re-run the installer, or DM Gaurav if it keeps failing."
fi

echo ""
echo "\${BOLD}\${GRN}🎉 Installation complete — 2 skills installed\${OFF}"
echo ""
echo "Next steps:"
echo "  1. Open Claude Code in your WSL terminal"
echo "  2. Try one of:"
echo "       \${BOLD}/classify-inspiration\${OFF}       (classify a URL queued from Immuvi dashboard)"
echo "       \${BOLD}/clickup-creative-pipeline\${OFF}  (bulk-classify a ClickUp list with Drive-Linked tasks)"
echo ""
echo "If ~/.local/bin isn't permanently on PATH, add this to ~/.bashrc:"
echo "  echo 'export PATH=\\"\\$HOME/.local/bin:\\$PATH\\"' >> ~/.bashrc"
echo ""
`;
}

// ────────────────────────────────────────────────────────────────────────────
// Utilities used by both installer builders (must be module-scope so the
// helper functions can access them — this bit us with a ReferenceError
// when sq() was scoped to handler() and called from buildMacInstaller).
// ────────────────────────────────────────────────────────────────────────────

// bash-safe single-quote escape: wraps the value in '...' and escapes any ' inside.
function sq(s) { return "'" + String(s).replace(/'/g, "'\\''") + "'"; }

// PowerShell single-quote escape: wraps in '...' and escapes ' by doubling it
// (PowerShell's rule for literal strings). Safe for arbitrary untrusted input.
function psq(s) { return "'" + String(s).replace(/'/g, "''") + "'"; }

function timingSafeEqual(a, b) {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) return false;
  let diff = 0;
  for (let i = 0; i < ab.length; i++) diff |= ab[i] ^ bb[i];
  return diff === 0;
}
